-- ============================================================
-- MIGRASI BARU PENDAFTARAN SIMRS
-- Database: rumah sakit (MySQL)
-- ============================================================

-- 1. Modifikasi tabel pasien
ALTER TABLE pasien MODIFY COLUMN ALAMAT_PASIEN VARCHAR(255) DEFAULT NULL;
ALTER TABLE pasien ADD COLUMN NIK VARCHAR(16) DEFAULT NULL AFTER ID_PASIEN;
ALTER TABLE pasien ADD COLUMN NO_TELP VARCHAR(20) DEFAULT NULL AFTER ALAMAT_PASIEN;
ALTER TABLE pasien ADD COLUMN PROVINSI VARCHAR(50) DEFAULT NULL;
ALTER TABLE pasien ADD COLUMN KOTA VARCHAR(50) DEFAULT NULL;
ALTER TABLE pasien ADD COLUMN KECAMATAN VARCHAR(50) DEFAULT NULL;
ALTER TABLE pasien ADD COLUMN KELURAHAN VARCHAR(50) DEFAULT NULL;
ALTER TABLE pasien ADD COLUMN JENIS_PEMBAYARAN VARCHAR(20) DEFAULT 'Umum';
ALTER TABLE pasien ADD COLUMN NO_BPJS VARCHAR(20) DEFAULT NULL;
ALTER TABLE pasien ADD COLUMN NAMA_ASURANSI VARCHAR(50) DEFAULT NULL;
ALTER TABLE pasien ADD COLUMN NO_POLIS VARCHAR(30) DEFAULT NULL;
ALTER TABLE pasien ADD COLUMN KONTAK_DARURAT_NAMA VARCHAR(50) DEFAULT NULL;
ALTER TABLE pasien ADD COLUMN KONTAK_DARURAT_TELP VARCHAR(20) DEFAULT NULL;

-- Tambah Unique Constraint untuk NIK
ALTER TABLE pasien ADD UNIQUE KEY uk_nik (NIK);

-- Update data pasien lama dengan NIK dummy agar tidak NULL dan tidak bentrok
UPDATE pasien SET NIK = '1234567890123451' WHERE ID_PASIEN = 'RM001';
UPDATE pasien SET NIK = '1234567890123452' WHERE ID_PASIEN = 'RM002';
UPDATE pasien SET NIK = '1234567890123453' WHERE ID_PASIEN = 'RM003';

-- 2. Modifikasi tabel pendaftaran
ALTER TABLE pendaftaran ADD COLUMN TANGGAL_KUNJUNGAN DATE DEFAULT NULL AFTER JAM_PENDAFTARAN;
ALTER TABLE pendaftaran ADD COLUMN SESI_KUNJUNGAN VARCHAR(20) DEFAULT NULL AFTER TANGGAL_KUNJUNGAN;

-- Update data pendaftaran lama dengan default tanggal daftar
UPDATE pendaftaran SET TANGGAL_KUNJUNGAN = DATE(TANGGAL_DAFTAR), SESI_KUNJUNGAN = 'Pagi' WHERE TANGGAL_KUNJUNGAN IS NULL;

-- 3. Modifikasi tabel users
ALTER TABLE users MODIFY COLUMN role VARCHAR(20) NOT NULL DEFAULT 'pasien';
ALTER TABLE users ADD COLUMN ID_PASIEN VARCHAR(10) DEFAULT NULL AFTER ID_DOKTER;
ALTER TABLE users ADD CONSTRAINT fk_user_pasien FOREIGN KEY (ID_PASIEN) REFERENCES pasien(ID_PASIEN) ON DELETE SET NULL;
